### ISSUE TITLE
Motion agnostic interactions

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#117]
# General Description
A person with a physical disability may want to interact with items in an immersive environment in a way that doesn't require particular bodily movement to perform any given action.

**REQ 2a**: Allow the user performing an action in the environment, in a device independent way, without having to do so physically.

**REQ 2b**: Ensure that all areas of the user interface can be accessed using the same input method.

**REQ 2c**: Allow multiple input methods to be used at the same time.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
As noted on call 6/8: This was categorized as _relevant for XR captioning_ because XR is an immersive environment where motion is a presumed prerequisite aspect.  It follows that motion agnostic interactions are are more of a challenge for XR captioning as compared to  traditional captioning (where this requirement is probably not an issue at all).
