### ISSUE TITLE
Routing to second screens

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#129]
# General Description
A deaf-blind user communicating via a RTC application in XR may have sophisticated 'routing' requirements for various inputs and outputs. 

**REQ 14a:** Allow the user to route text output, alerts, environment sounds and audio to a braille or other devices.

- [https://www.w3.org/TR/xaur/#user-needs-definition](https://www.w3.org/TR/xaur/#user-needs-definition)

# Functional Performance
Please see [EN 301 549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) for descriptions of functional performance areas.

- [ ] Usage without vision
- [ ] Usage with limited vision
- [ ] Usage without perception of colour
- [ ] Usage without hearing
- [ ] Usage with limited hearing
- [ ] Usage without vocal capability
- [ ] Usage with limited manipulation or strength
- [ ] Usage with limited reach
- [ ] Minimize photosensitive seizure triggers
- [ ] Usage with limited cognition
- [ ] Privacy

**Comment by bruce-usab** [comment]
As noted on call 6/8:  This was put into _traditional captioning_ as the ability to route captions to a second screen is something that would be expected outside of an XR setting.

**Comment by bruce-usab** [comment]
Per call 6/15, we are trying to distinguish this requirement from #113 as it is a little simpler.  This requirement may or might not include routing captions to a different app (e.g., using Discord for chat while gaming, rather than using in-game chat).

Since this requirement applies to dynamic braille displays, the term <q>screen</q> should be not be taken literally.
