### ISSUE TITLE
Important requirements burried in the Scope section

### ISSUE THREAD

**Issue by SteveALee** [w3c/silver#188]
As originally identified by Lisa Sleeman, the following text in the Scope section should be moved to the requirements section. Otherwise it is liable to being missed.

"Disability Needs: An improved measurement and conformance structure that includes guidance for a broad range of disabilities. This includes particular attention to the needs of low vision and cognitive accessibility, whose needs don't tend to fit the true/false statement success criteria of WCAG 2.x."

If this cannot be done until FPWD then I suggest it's given a full review for how it sits in the correct context of the Requirements section

**Comment by jspellman** [comment]
In the Silver meeting of 1 December 2020, we resolved to change the Requirement "Multiple Ways To Measure" to "Broader Disability Support" as follows: All Silver guidance has tests or procedures so that the results can be verified. In addition to the current true/false success criteria, other ways of measuring (for example, rubrics, sliding scale, task-completion, user research with people with disabilities, and more) can be used where appropriate so that more needs of people with disabilities can be included. This includes particular attention to accessibility for individuals with low vision, cognitive and learning disabilities, whose needs can be better met with a broader testing approach.

**Comment by jspellman** [comment]
Resolution from the Silver meeting of [22 January 2021](https://www.w3.org/2021/01/22-silver-minutes.html#r01): 
4.1 Broad disability support
Silver guidance includes tests and other evaluation methods. Some guidance may use true/false verification but other guidance will use other ways of measuring and/or evaluating where appropriate so that more needs of people with disabilities may be included (for example: rubrics, sliding scale, task-completion, user research with people with disabilities, and more). This approach includes particular attention to people whose needs may better be met with a broad testing strategy, such as people with low vision, limited vision, or cognitive and learning disabilities.
