### ISSUE TITLE
Requirements doc: number agreement - minor editorial decision

### ISSUE THREAD

**Issue by mbgower** [w3c/silver#25]
> The Web Content Accessibility Guidelines (WCAG) 2.0 were designed to be technology neutral, and has stayed relevant for over 10 years.

This sentence illustrates inconsistent use of _guidelines_ as both a plural -- "were designed" -- as well as a singular term -- "has stayed". I think it reads more logically as a plural, and would recommend that be used throughout the doc.

> The Authoring Tool Accessibility Guidelines (ATAG) 2.0 has been 

to become
> The Authoring Tool Accessibility Guidelines (ATAG) 2.0 have been 

etc

**Comment by jspellman** [comment]
Thanks @mbgower!  There was a style guide decision made many years ago by EO (?) that we should use singular.  What I do remember clearly is the number of times I was admonished for using the incorrect verb tense. Despite my best efforts. I don't always catch the occasions that I automatically use the plural simply because "Guidelines" ends with an "s".

**Comment by mbgower** [comment]
The abbreviation "WCAG 2.0" reads fine as a singular (where it is easier to think of it as a 'version') but it's certainly a little unintuitive for the spelled out name. I assume the rationale is that it is a single publication/standard. It would be nice to work some nuance into those style guides to handle usage (i.e., spelled out, plural; abbrevation, singular).

**Comment by slauriat** [comment]
RESOLUTION: To use the singular and plural definitions of WCAG 3.0 from [the Style Guide](https://www.w3.org/WAI/GL/task-forces/silver/wiki/Silver_Style_Guide)
