### ISSUE TITLE
ARIA under "Development" category

### ISSUE THREAD

**Issue by a11ydoer** [w3c/silver#27]
Hi Mike, 
Thanks for the great work. 
I was told to create the issue for the questions I have for the prototype. 
https://mikecrabb.github.io/silver_flavor_prototype/1-1-1/
1. It does not make sense to me that ARIA is under the "development" category with specific technologies such as pdf, Silverlight and more.
2. What do "item A" and "item B" mean under the "Planning"?
Jemma

**Comment by mikecrabb** [comment]
Hey Jemma! Thanks, quick answers to your questions:
1. I had taken the category names from the  [W3 Getting Started With Accessibility Guide](https://www.w3.org/WAI/EO/wiki/Start_with_Accessibility) so under that it is more of a Development concern than any of the others (I think?) If you have any suggestions as to a better category for it to be under (or even a different category structure) then please leave a suggestion below and I can knock up a prototype to see how it looks 😸 
2. They are just placeholders at this point, again, any suggestions for what can go here in the interm would be appreciated

**Comment by mikecrabb** [comment]
Maybe a hierarchical thing under static web? It is an HTML concern but its more specific than just HTML/CSS? [WCAG 2 splits techniques](https://www.w3.org/TR/WCAG20-TECHS/) into:
- General
- HTML
- CSS
- Client Side Scripting
- Server Side Techniques
- SMIL Techniques
- Plain Text Techniques
- ARIA Techniques
- Flash Techniques
- Silverlight Techniques
- PDF Techniques

**Comment by jspellman** [comment]
I don't think ARIA belongs under static web, since it was developed to address the dynamic web.  But ARIA also applies to other technologies beyond HTML, even if HTML is the most commonly used technology for ARIA.   I think this is an IA issue how Silver should integrate the guidance that is currently under Techniques.  At the moment, I think that ARIA is a technology that should be grouped with the different technology guidance, but I'm open to seeing a different organization.

**Comment by jspellman** [comment]
Thank you for your comment. We have closed this issue because we believe this issue has been addressed or is no longer relevant. If you believe this issue should be reopened, please open a new issue and reference this issue. If you have trouble, contact a WCAG 3 editor.
