### ISSUE TITLE
Guideline "Clear Words"

### ISSUE THREAD

**Issue by caztcha** [w3c/silver#289]
WCAG 3.0 の Guidelines のひとつに、"Clear Words" が今回、盛り込まれています。平易で明快な言語表現によってコンテンツを記述することは、特に認知に問題のある利用者にとっては有益なので、このガイドラインが盛り込まれることは賛成です。

一点、気になったのが、このガイドラインのテスト用に、Simple Writer のようなテストツールが紹介されていることです。このようなテストツールの存在はありがたいですが、英語のみ、というのが気になります。WCAG は国際的なガイドラインなので、多言語についてもある程度考慮した形で、outcome / method がまとめられることを願っています。

// Excuse me for posting in Japanese, @MakotoUeki -san. :)

**Comment by lauracarlson** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by lauracarlson** [comment]
Copied from translation tool:

"'Clear Words' is now included in one of the WCAG 3.0 Guidelines. I agree with this guideline, as describing content in plain and clear linguistic expressions is particularly beneficial to users with cognitive problems.

One thing I was curious about was the introduction of test tools like Simple Writer for testing this guideline. I am grateful for the existence of such a test tool, but I am concerned that it is only in English. Since WCAG is an international guideline, I hope that outcomes / methods will be put together with some consideration for multiple languages."

**Comment by jmcsorle** [comment]
Thank you for your comment. We agree with you that this work must occur for all languages. Simple Writer is an example of a proof-of-concept tool to support the use of clear words. We would like for tools to be developed and available for all languages. One suggestion we are discussing is developing tools to enable organizations / website authors to upload their own dictionaries that can be customized by language.

**Comment by lauracarlson** [comment]
Suggest adding at the end of the [Draft Response](https://github.com/w3c/silver/issues/289#issuecomment-820764247-permalink): "We will tag this issue to come back it to at an appropriate point later."

**Comment by alastc** [comment]
The response above was approved by the group: https://www.w3.org/2021/04/27-ag-minutes.html#item02
