### ISSUE TITLE
Outcome measure for visually distinct headings

### ISSUE THREAD

**Issue by sdw32** [w3c/silver#330]
From https://www.w3.org/WAI/GL/WCAG3/2020/outcomes/uses-visually-distinct-headings 

> Uses visually distinct headings so sighted readers can determine the structure.

How can this outcome be measured in an objective way to determine conformance? How much difference between headings is enough difference?

The APCA tool used in the visual contrast of text section may be able to help quantify this. https://www.myndex.com/SAPC/

Alternatively, perhaps something like ... 
Measure the following for a normally sighted user:
- the maximum viewing distance at which the body text can be read at maximum speed 
- maximum viewing distance at which h3 text is legible
- maximum viewing distance at which h2 text is legible
- maximum viewing distance at which h1 text is legible

The guideline could then offer appropriate ratios between these distances, something like each distance should be 150% of the previous.

**Comment by Myndex** [comment]
HI @sdw32 thank you for commenting

### "Visually distinct headings" is not a product of the Visual Contrast subgroup

I believe it is essentially a placeholder as a part of semantic structure. As far as I can tell it is not otherwise supported (not clear?? researched?). This is one example of crossovers, that Silver is intended to be flexible enough to handle. Demonstrating this is my guess why it was included at the last minute.

One of the open agenda items in the Visual Contrast Subgroup is fixing this to bring it in line with the rest of the readability and visual accessibility research. 

> _Measure the following for a normally sighted user:_
Arbitrary viewing distances for different headings is not instructive and not a useful path here. Classical design is the place to start, as these general aspects of design have been largely worked out for centuries.

Thank you,

Andy


_Andrew Somers_
_W3 AGWG Invited Expert_
_Myndex Color Science Researcher_
https://www.myndex.com/APCA/simple

**Comment by ChrisLoiselle** [comment]
@jspellman This is ready for survey. Pertains more to heading related guidelines than visual contrast of text.

**Comment by jenstrickland** [comment]
Draft Response:

The structured content sub-group agrees will reflect upon these comments and will include them in our work. Thank you for your insightful comments!

**Comment by WilcoFiers** [comment]
Thank you for reviewing and commenting on the WCAG 3 first public working draft. We have an [updated working draft](https://www.w3.org/TR/wcag-3.0/) and the group is starting a new workflow process. To facilitate this transition we have recorded your concern as part of w3c/wcag3#19. You can engage in the discussion around this issue there. 

Please continue to review future drafts and provide feedback through [Github](https://github.com/w3c/wcag3).

If you disagree with closing this issue, please reopen it and add your reasons for reopening it to the comments.
