### ISSUE TITLE
What are the units of luminance contrast calculated in the APCA tool?

### ISSUE THREAD

**Issue by sdw32** [w3c/silver#335]
The APCA tool provides a value for luminance contrast. The maximum absolute value of this luminance contrast appears to be 109 for white #fff on black #000, and the minimum absolute value is 0, if the foreground and background colour are the same.

Many kinds of contrast are expressed as a percentage, but this one doesn't appear to be a percentage.  

From https://www.myndex.com/WEB/WCAG_CE17polarity I found the equation
 
> CPredictedContrast = LSbackgnd - LStext

In this case, does CPredictedContrast have the same units as luminance, and is this candela per square metre?

Given that the APCA luminance contrast appears to vary between 0 and something close to 100, people may assume that it's a percentage, even if it's not. They may then get confused when the number goes over a hundred. So, if it's not a percentage, I would suggest making this explicit, and maybe dividing all the numbers by 10 so that you get a value in the range 0-10, or multiplying all numbers by 10, so you get a value in the range 0-1000.

**Comment by Myndex** [comment]
@sdw32 thank you for commenting

> _"The APCA tool provides a value for luminance contrast. "_

No, the APCA stands for **Advanced Perceptual Contrast Algorithm**. While it reduces all colors to luminance in the first stage of processing, it is not reporting luminance contrast.

It is reporting PERCEPTUAL contrast, based on interdependent and polarity specific perceptual lightness values. APCA is derived from the SAPC model, SLUV Advanced Perceptual Contrast, a perceptual color and contrast appearance model (still in development) that has specific weightings for certain vision and impairment types.

**The current G series evaluation constants are live here:**  https://www.myndex.com/SAPC/


> _"Many kinds of contrast are expressed as a percentage, but this one doesn't appear to be a percentage."_

It is "essentially" a percentage, but as you know it is labeled as L<sup>c</sup> to distinguish it from the many other percentage reporting models. Percentages can exceed 100. In the case of APCA, there is scaling to make some fine adjustments to the perceptual uniformity and to align certain key levels with convenient easy to remember values. The current scaling is sets level as per:

## GENERAL GUIDELINES on APCA LEVELS

- **90** • Suggested for extremely thin fonts, also 90 is a suggested _maximum_ for very large and bold fonts, and large areas of color. 

- **75** • Preferred level for columns of body text. Also, use for any text where readability is important.

- **60** • The _minimum_ level recommended for content text, that is, text you want people to read. "Sort of" like the old 4.5:1 in WCAG2, except perceptually uniform up and down the scale.

- **45** • The minimum level for large text such as big headlines, and semiotic non-text (icons with meaning, but no small or fine details) "Sort of" like the old 3:1 in WCAG2.

- **30** • The absolute minimum for any text, including text for spot reading, place holder text, etc. Large non-text content can be below this however.

- **15** • The absolute minimum for any large non-text that needs to be _discernible_, but does not convey specific meaning (i.e. no icons), and does not include fine details, such as buttons (not including any text). Designers should treat anything below this level as _invisible_, as it will not be visible for many users.

### Threshold levels
In the very low contrast regions, the values are semi-aligned to clinical type levels (CS), however it is important to note that due to the low resolution of 8 bit monitors, actual clinical use is prohibited for the sRGB version.


> _"They may then get confused when the number goes over a hundred."_

No, people are smart.


Thank you,

Andy


_Andrew Somers_
_W3 AGWG Invited Expert_
_Myndex Color Science Researcher_
https://www.myndex.com/APCA/simple

**Comment by alastc** [comment]
What I'm taking from this question and answer is that the WCAG 3.0 documentation should include some content on how to interpret APCA / SAPC values. The list above is a good starting point.

Also, whilst people are smart, I run a lot of accessibility training, and often this is one of 50 things they need to think about. So smart yes, but also busy and distracted. Anything we can do to make it easier to use/understanding is helpful.

**Comment by bruce-usab** [comment]
I must say that I do like that it is working out that the <q>minimum grade</q> to shoot for is an APAC value of 60.  It leaves a lot of room (and maybe incentive feelings from grade school) for improvement!

**Comment by Myndex** [comment]
Hi Bruce @bruce-usab 

> I must say that I do like that it is working out that the minimum grade to shoot for is an APAC value of 60. It leaves a lot of room (and maybe incentive feelings from grade school) for improvement!

And there are probably a dozen reasons that 60 was chosen as the "touchstone" value, many I have already mentioned above. They are not "arbitrary" but part of the total concept of creating a easy to use and robust contrast methodology.

The "most current" scaling, which at this point I think will not change until after the next working draft (i.e. I am about to mark it as stable and move it into the APCA tool) is the G series constants, live at the SAPC development site:

https://www.myndex.com/SAPC/


Thank you!

Andy

**Comment by bruce-usab** [comment]
@Myndex how are you writing Lc in markdown?  I tried quoting your reply, but the formatting was lost.  Here is one using HTML sup tag:  L<sup>c</sup>

**Comment by Myndex** [comment]
HI Bruce @bruce-usab 
> @Myndex how are you writing Lc in markdown? 

Yes, for the sup c in L<sup>c</sup> just use the standard HTML tags. Not "critical" Lc has the same meaning. But L<sup>c</sup> is intended to look similar to `L* ` which is perceptual lightness in CIELAB and LUV, and L<sup>c</sup> in part traces its roots to L*.

**Comment by ChrisLoiselle** [comment]
@jspellman This is ready for survey. If additional context is needed on the next version of WCAG 3.0, we can add the documentation that is referenced on https://www.myndex.com/SAPC/, as @Myndex states in his replies.

**Comment by sdw32** [comment]
Thanks for all the replies, I have read this discussion with interest. I must admit I'm still slightly confused as to whether the perceived contrast reported by the tool is a percentage, or just an index. This page https://www.w3.org/WAI/GL/task-forces/silver/wiki/Visual_Contrast_of_Text_Subgroup#Table_with_Selectable_Text 
has text like this (which I gather is now redundant, but my point remains regarding the percentage sign)

> APCA 80% is similar to WGAG 7:1 with a very light background.
>APCA 60% is similar to WGAG 4.5:1 with a very light background.
>APCA 40% is similar to WGAG 3:1 with a very light background.
>Other comparisons:
>APCA 100% is similar to the 10:1 of some other methods, widely considered to be an ideal contrast for columns of body text with a normal weight font.
>APCA 20% is similar to the 2:1 of some other methods, considered to be a "hard limit" minimum by some standards.
>APCA 10% is similar to 1.5:1, and is close to the visibility threshold for some impairment types. Designers should consider any contrast lower than this to be invisible.

For me, including the percentage sign makes it much more meaningful than just saying it's a 'contrast score', and I would suggest to add the percentage sign after the number in the APCA tool.

@myndex you can see I got confused by Lc being used to mean 'perceived lightness contrast', I had thought this stood for luminance contrast. For perceived lightness contrast I would suggest  using all three letters PLC in some form, to better distinguish it from luminance contrast.

Regardless of whether it's a percentage or an index, any such scale is usually created by calibrating some of the points to meaningful values. In the latest calibration I gather that it's primarily so that 45,60,75 etc. line-up in some way with the old 3:1, 4.5:1 (for some limited range of colours, as of course the WCAG 2.x is rubbish). 

It surprises me that the scale is calibrated to midpoint values in this way, if you take anything else like temperature it's the 0 and 100 values that are meaningful end points, and everything in the middle just scales accordingly. In my opinion, it would make more sense to equivalently set the anchor points as setting 0% perceived contrast means two colours that are the same, and 100% contrast means 'as much perceived contrast as you get on a monitor ', which is therefore #000 against #fff. 

Given that perceived contrast now tops out at 108 now anyway, I wouldn't think it would make much difference to simply scale all the current scores by 100/108, so that they fall in the range 0-100% Probably the existing thresholds can stay as they are, although some of them may change when rounded to the nearest five.

I note @Myndex stated in his reply that evidence from early adopters suggests that no one has had any issue with perceived contrast going over a hundred, but if I was teaching this to someone, I would certainly rather explain what 100% meant to start with, and then explain the other threshold values afterwards.  It's also particularly relevant regarding the discussion that in fact 90% perceived contrast is better for readability than 100%!

**Comment by bruce-usab** [comment]
@sdw32 the APCA number is not a percentage.  That wiki page using a percent symbol was/is a work in progress.

> Given that perceived contrast now tops out at 108 now anyway, I wouldn't think it would make much difference to simply scale all the current scores by 100/108, so that they fall in the range 0-100%

Sorry, but I think that would be terrible.  First, just the idea of <q>100% contrast</q> is very problematic.  The use of the percent symbol (when L<sup>c</sup> is _not_ a percent) just because the numbers we are currently using are sort of in the range of  0-100 and we use percent for other numbers.  How about we use $ or &cent; since those are also 0-100?

**Comment by sdw32** [comment]
@bruce-usab thanks for your comment. I don't think you can add any other symbol like $ as it's a dimensionless index or score (at least that's what I believe it is!)

As another alternative for discussion, perhaps all the numbers can be divided by 10 so that you get a score out of 10 (although the actual maximum would in fact be 10.8, unless the rescaling was performed to bring it in the range 0-10)

**Comment by sdw32** [comment]
@bruce-usab The meeting was 29 July  at 9 AM ET. I'm afraid I didn't record the attendees of the meeting, perhaps Chris can supply this?

**Comment by svgeesus** [comment]
> @Myndex you can see I got confused by L<sup>c</sup> being used to mean 'perceived lightness contrast', I had thought this stood for luminance contrast. For perceived lightness contrast I would suggest using all three letters PLC in some form, to better distinguish it from luminance contrast.

In color science, luminance is indicated by Y ( the Y in CIE XYZ) while perceptual lightness is typically indicated by L or L<sup>*</sup> (the L in CIE Lab, OKLab, CIE Luv, and so on). The fact that WCAG 2.x used L for Luminance, which perhaps seemed easier to remember at the time, now makes it more complex when WCAG 3.x discusses both Luminance and Lightness.

Anyway, just to point out that I found L<sup>c</sup>  to be clearly understandable as Lightness contrast.

**Comment by svgeesus** [comment]
Should the title of this issue be altered to reflect discussion, or the issue closed?

**Comment by sdw32** [comment]
The issue can be closed. Regarding my original question in the title, once it's clear that it's an index that represents the Perceived Lightness Contrast, this would obviously have no units, it's just an index. I had originally made a strong case that the index should go between 0 and 100, to match the typical range for other indexes. However, @Myndex made a strong counter argument that the current scaling gives appropriate and easy to remember thresholds in the range 15, 30, 45, 60, 75 and 90. re scaling the range between 0 and 100 would negatively impact either the accuracy or memorability of these thresholds, and I agreed with @myndex that this was more important than keeping the index between zero and 100.
