### ISSUE TITLE
3.1 schrodinger's conformance

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/silver#40]
Section 3.1 says the following:
> Different guidance has potential for different measurement. For example, it may describe "minimal" and "better" methods of conforming to a requirement or allow user testing and usability testing as a method of conformance.

I don't see how this idea could work in practice. So this is suggesting that if there are five ways to measure something, and if something passed in 3 of them, and failed in 2, it would be simultaniously conforming and non-conforming?

This concerns me for two reasons. Firstly because this has a high probability of making Silver more complex than WCAG 2. It seems to me that that's likely to end up just increasing cost and decreasing adoption. 

Secondly, while I think doing usability testing is commendable, it has the massive downside that those test results aren't going to be consistent. Someone can do the same usability study twice and get vastly different results. It seems to me that the actual implication of this is that we'd **abandon the principle of repeatable tests**. I'm open to the suggestion, but I think that's only really feasible if we find that this would still be viable in a legal context.

**Comment by detlevhfischer** [comment]
I think the bit quoted above ("describe "minimal" and "better" methods of conforming to a requirement or allow user testing and usability testing as a method of conformance.") includes two very different things. 

There could be ways of reflecting the better quality of certain methods of conforming in some way (say, a site offering skip links to meet 2.4.1 in addition to landmarks may somehow be rewarded beyond just passing because it better accommodates the needs of keyboard users). 

The second aspect is entirely different. I do not think that a conformance statement should in any way depend on what method of evaluation has been used. Whatever we end up with in Silver, I think the result of a conformance test must reflect the **content**, not the efforts that have been made to arrive at or improve that content. However, an evaluation result may reflect **in addition** to a conformance statement that the site has undergone user testing as part of the evaluation (say "Passes WCAG-AA, Usability-tested").

**Comment by jspellman** [comment]
This comment and questions pre-date the FPWD conformance model.  The comment is valuable and we will keep it in mind in the long run.  We attempted to address these issues in the FPWD conformance model. Could you please open a new issue to cover any you think are still unresolved?
