### ISSUE TITLE
Email: Siteimprove Comments on WCAG 3.0 Draft (4 - WCAG 3.0 success levels are impractical)

### ISSUE THREAD

**Issue by cwadamsoforacle** [w3c/silver#510]
[Comment from email:](https://lists.w3.org/Archives/Public/public-silver/2021Apr/0031.html)
WCAG 3.0 success levels are impractical
[WCAG 3 comments_Siteimprove_Codebusters_April7_2021.docx](https://github.com/w3c/silver/files/6281636/WCAG.3.comments_Siteimprove_Codebusters_April7_2021.docx)

We expect there to be little interest in WCAG conformance beyond the minimum level required by the law. This, we must say, has been and remains the case with WCAG 2.x; and given the sheer effort of passing the qualitative and user-testing-based silver ang gold levels in 3.0, striving for a greater WCAG level amounts to a major undertaking in which only very few organizations are in the real world interested. We therefore suggest more emphasis is put on simplifying and clarifying the minimum WCAG level that in our experience caters to 99% of WCAG applications (as has now been successfully done in WCAG 2.x with the A and AA nomenclature).
Moreover, the terminology of bronze, silver and gold levels fits poorly for the intended use of WCAG. The terms are not professional and are unheard of in conformance specifications. That is, in the European cultural and linguistical context the terminology may even threaten to undermine WCAG 3.0 credibility amongst adopters. The draft should revert back to employing the WCAG 2.x  A, AA and AAA level in its terminology for conformance.

**Comment by cwadamsoforacle** [comment]
Thank you for your comment. Project members are working on your comment. You may see discussion in the comment thread and we may ask for additional information as we work on it. We will mark the official response when we are finished and close the issue.

**Comment by cwadamsoforacle** [comment]
Draft response:

The working group is exploring approaches and conformance models that can meet the needs of regulators and also provide mechanisms and incentives which encourage adopters to go above and beyond minimum regulatory requirements.  The successes of WCAG 2.x offer instruction on creating guidance that can be used by regulators, and will continue to inform and guide the working group in the development of WCAG 3.  As this is a first draft, there is opportunity to discuss the terminology used to describe the levels and pick terms which have meaning and value world-wide.

**Comment by jspellman** [comment]
I agree with the answer. I think we need to research the [Site Improve comment](https://github.com/w3c/silver/issues/510#issue-853936780)  that the titles are unprofessional in the EU. I recommend that we flag this issue for further followup such as approaching the appropriate regulators to ask if the names Bronze Silver Gold would be considered unprofessional. Is the Leeds Green Building model accepted in the EU and does it have different names? Also notes that AGWG members volunteered to reach out to contacts and ask them about this in [AGWG meeting](https://www.w3.org/2021/04/20-ag-minutes.html#t04).

**Comment by simaocampos** [comment]
David Fazzio asked me to comment (I am from ITU). Personally I am ok with A, AA and AAA - they are consistent with the energy efficiency labels that we see in Europe, so it is "natural" to think AAA is better than AA that is better than A.
That said, I do not see a negative connotation for bronze/silver/gold/platinum, but this is a personal perception. From a standardizer perspective: I'd prefer to see the current letter designations kept, because WCAG already uses it and people that study it became familiar, and for the sake of backward "semantic interoperability" I'd not change it. Unless of course if the letter level designations caused problems, or in the new WCAG the conformance levels do not map with what you have before - if this were to be the case, keeping A/AA/AAA would be comparing apples to oranges across WCAG versions, and then change inthe designation would be a good idea. Keep up the good work!
