### ISSUE TITLE
Backwards compatibility post-WCAG 3.0 publication

### ISSUE THREAD

**Issue by alastc** [w3c/silver#569]
In the requirements document it drops the 'backwards compatibility', which makes sense when going from 2.x to 3.0.

However, what about updates to WCAG 3? I think we need to agree that the intent is to either:

- Keep backwards compatibility in the 3.x version, OR
- Have a mechanism to notify people of incompatible updates.

**Comment by Myndex** [comment]
> _This is essentially a copypasta of my thoughts I posted in 424_

# Interversion & Intraversion Compatibility Considerations

## Some Definitions
- **Backwards compatible:** 
    - **Inter** version: a site that passes WCAG 3.0 at some pre-determined level, will automatically pass all tests of WCAG 2.0 (or 2.x?) at the AA level.
    - **Intra** version: a site that passes future WCAG 3.1 will automatically pass all tests of WCAG 3.0 at the same conformance level.

- **Forwards compatible:** a site that passes WCAG 2 at the AA level would automatically pass all tests at least at the lowest level of conformance of WCAG 3.0.

- **Forward grandfathering:** pages with a "grandfathered" meta tag are tested as 2.0, AND/OR exception(s) are added to WCAG 3.0 to allow a WCAG 2.x AA site to pass 3.0 with those exception(s) at the lowest level of conformance.

- **Reverse grandfathering:** (is this grandchild-ing??): future pages with a "grandchild" meta tag designed to pass a given version's guideline such as 3.1, wherein some revised tests break or are partially incompatible with an earlier intraversion such as 3.0, a reverse grandfathering would pass the specific earlier tests, but using the _revised_ test criteria.

- **Sectional transitioning:** or "cascade" transitioning. A site transitions from WCAG 2.x to WCAG 3.0 (or 3.0 to 3.1) on a **_per SC_** or per section basis.

-------
_Note: originally written to discuss the 2.x to 3.0 transition, but applies to many 3.x to 3.y transitions_

-----
## DISCUSSION
### _BACKWARDS_ 
- Backwards compatible is a non-starter as it would require portions of WCAG 2.x to be re-written or specific exceptions made to accommodate the newer technologies of WCAG 3.0. As I understand it, even a WCAG 2.**3** can not change any existing SCs or override them.
    - Case in point, WCAG 2 contrast has some issues calculating some contrasts. False passes are not an issue as APCA would correctly fail those. But certain bright colors will pass with APCA as they should pass, nevertheless due to the math, WCAG 2 would indicate a fail for these.
    - Myself **I object to a backwards compatible WCAG 3** if WCAG 2 can not be modified, I think it would be terrible to hobble WCAG 3 guidelines into those SCs.
    - On the other hand, if there was a WCAG 2.3 that included backwards compatible "overrides" such as to allow WCAG 3.5 to override 1.4.3 and 1.4.11 etc., this might be more palatable...
    -ut what utility is there for taking a site that passes 3.0 and testing it for 2.1 ?? 

### _FORWARDS_ 
- 2.x to 3.0 forwards compatible is doable with the caveat that the WCAG 3.0 guidelines would have to have a conformance level that was structured to pass WCAG 2. We developed that kind of conformance for visual contrast, making "score 1" a WCAG 2 catch all, and in most cases would be effective, but if someone had designed a passing site on the edge of conformance, they could still fail the score 1 level.
    - Right now I'd call this the _"well designed sites that pass WCAG 2 AA would pass 3.0 at least at score 1"_ model.
    - The drawback is making conformance potentially weak in some areas, or causing other conflicts.
- Intra-versional 3.x to 3.y may be a given, but consider the grandfather/grandchild clauses below.

### _GRANDFATHERING_ 
- Grandfathering forward from WCAG 2.x, presumably with some restrictions, is the most practical and simplest IMO, while doing the best to maintain integrity of WCAG 3.0. In this case no guidelines are "weakened" just to allow a pass.
    - But instead, a page with a... **`  <meta wcag3="2.0-grandfathered">   `** ....2.0-grandfathered tag gets tested under 2.0, otherwise gets tested under 3.0. Presumably some SCs might be excluded from grandfathering.
    - Alternately or inclusively each guideline might have specific items that are ecluded as grandfathered.
    - grandfathering should probably have an end condition, such as a page or asset is substantially changed in form, or by a certain future date, or declared "archival" and frozen in state. 
- **Intra-versional** 3.x to 3.y grandfathering permits the sectional adoption of new guidelines, and conformance of archival pages and sites continue.
    - IMO forcing compliance to new guidelines on legacy or archival pages would have the chilling effect of those pages simply being deleted. 
    - If archival or legacy content is presented within the view of a new site CSS design, then the new relevant guidelines should most likely apply, though there are some stumbling blocks here.

### _GRANDCHILDED_
- Applies to intra-versional changes. Considering the fluid nature of technology, this allows a future version to supersede a current version, and further allows early adopters to incorporate new guidelines without a penalty due to a breaking change to the relevant previous guideline by a new or improved guideline.
- By example: there has been a massive technology shift since the WCAG 2 contrast specs were adopted.
    - The new WCAG 3 contrast method in APCA is consistently more accurate, as it's based on the latest vision science, and it is more flexible as a result.
    - But while the WCAG 3 contrast outperforms the old, the math of the old method sometimes rejects a color that should pass and so the results of WCAG 3 contrast can not be backwards compatible. 
    - If WCAG 2 had a "grandchild" provision, a new version of contrast could be adopted as a non-backwards compatible SC but without otherwise breaking the site.
- The unknowable nature of developing technology makes the need for some mechanism for backwards-breaking with newer/improved guidelines and expected necessity.
- This would be useful for early adopters and beta testers.

### _SECTIONAL_
- **Sectional transitioning:** or "cascade" transitioning. A site transitions from X -> Y on a **_per SC_** or per section basis.
    - This seems like a need or desired path for very large sites, and in markets where legal or contractual obligations are significant.
   - For example purposes only, let's say the site first wants to convert color and contrast, so they replace the 1.4.3 series of SCs with the 3.5 Visual Contrast. During this time, they could test for conformance using WCAG 3.0 Visual Contrast instead of the 1.4.3 series, but still use the WCAG 2.x SCs for other conformance categories that have not transitioned yet.
    - To support this workflow, some meta-tags are needed to indicate which spec a page should be tested under.
    - Such as ` <meta conformance="WG2.2 {all}    WG3.0{4.4,4.5}"> which cascades, latest overwrites earlier.
    - Such a provision would be to allow sites to flexibly adopt and move forward without fear of legal or contractual issues from the demands of a certified testing schedule,


Thank you for reading,

Andy

**Comment by chaals** [comment]
Given the time it takes to make updates, I prefer that WCAG 3 version updates are allowed to break backwards compatibility. To use the contrast example again, if we have WCAG 3.1 and then discover a more realistic measure of contrast and how it affects real people, that is incompatible with the one in WCAG 3.1, we should be free to put it into WCAG 3.2.

**Comment by chaals** [comment]
@Myndex wrote

> GRANDFATHERING
> Grandfathering forward from WCAG 2.x, presumably with some restrictions, is the most practical and simplest IMO, while doing the best to maintain integrity of WCAG 3.0. In this case no guidelines are "weakened" just to allow a pass.
> - But instead, a page with a... `<meta wcag3="2.0-grandfathered">` ....2.0-grandfathered tag gets tested under 2.0, otherwise gets tested under 3.0. Presumably some SCs might be excluded from grandfathering.

I don't think there is any real value in "grandfathering". Sites that pass WCAG 2.x (as with WCAG 1.0) continue to meet that standard. If they don't meet the new standard  because we have worked out a better way to remove some barrier to access, that was not known or widely required when they last updated their work, it is important to be clear that they have not implemented that.

So rather than "some SCs" being exempted, we should just be clear that WCAG 2.x conformance doesn't necessarily imply WCAG 3.x conformance.

For old unmaintained content, that provides a clear understanding, for old maintained content a new assessment can be done, and *if* anything needs to be changed to meet WCAG 3.x, that's an improvement we **want to encourage**.

**Comment by Myndex** [comment]
Hi @chaals 

> Given the time it takes to make updates, I prefer that WCAG 3 version updates are allowed to break backwards compatibility. ....., that is incompatible with the one in WCAG 3.1, we should be free to put it into WCAG 3.2.

Given that WCAG is an international standard, and codified into low in some jurisdictions, there are some not insignificant issues with such as approach. The result is a discordant environment where users in a given jurisdiction would then be unable to upgrade to incorporate more recent guidelines pending their local legislatures adoption, and then being forced to rush forward to catch up and conform.

**Comment by chaals** [comment]
We do not force anyone to adopt it in law, and we don't set anyone's timeline. We provide a technical description of what is necessary to ensure the best accessibility we know how to provide.

If that is going to be encoded into laws - at a schedule determined by each jurisdiction independently - it seems even more important that we work to make that technical description as accurate as possible.

Compromising our technical expertise to influence regulations is way beyond our scope of work, competence, or social remit, and we should be very careful to avoid ding so.

**Comment by Myndex** [comment]
> We do not force anyone to adopt it in law,.....Compromising our technical expertise to influence, or be influenced by, some subset of regulations....

This is not at all the point I was making, and not at all what I was talking about.

We have a responsibility toward making a stable, functional, and useable standard; it is a standard that is used internationally and is often used as the basis of law. Recognizing this, part of the responsibility is to avoid some laissez faire or capricious attitude toward the guidelines which is what you seem to be advocating.

**Comment by alastc** [comment]
I don't think anyone is advocating a laissez faire or capricious attitude, the discussion is around our scope and intent.

Advice we have had from people involved in the national legislation side of things is: Do not try to overlap with or predict the legislation.

They tend to work on even longer time-scales than ours, and at the point of creating the legislation they look at what is available and make a decision. E.g. 5 years after WCAG 3.0 is published, the US _might_ look at it for Section 508. 15 years later, they might look at WCAG 3.3, or we might have an 'evergreen' WCAG 3.0 that is significantly updated. TBD.

We have considered compatibility between 2 & 3, but do not wish to be restricted by that.

**The question for this thread** is whether future versions of WCAG 3.x are intended to be backwards compatible (in the sense that passing 3.1 would mean you pass 3.0). 

That does bring restrictions, we feel those quite strongly for SCs such as 4.1.1 Parsing, which (IMO) would not qualify to become an SC if we looked at it now, but we are stuck with it.

If we drop the requirement for backwards compatibility (which is what is in the requirements doc), then I'd like to add a requirement for some form of notification/mapping system for incompatible changes.

**Comment by chaals** [comment]
I'm strongly in favour of dropping the requirement for backwards compatibility between different versions.

I strongly agree with @alastc that if that requirement is dropped, there should be a clear explanation of any breaking change. (There should always be a human-written and clear explanation of changes between versions, IMHO).

And none of this should be interpreted to mean I don't think backwards compatibility is valuable. We should not break it unless there is a compelling to do so - but improving accessibility seems like a compelling reason.

**Comment by Myndex** [comment]
It has been brought to my attention that I am frequently misunderstood. Unfortunately, I'm the kind of person that gets "very triggered" when I am misunderstood. My solution has been to "write more"… But that fails because people really don't read the longer materials I provide. Yet so when I write short and compact, it seems to get misinterpreted!

It should be very clear from my initial post that I think backwards compatibility is a non starter for WCAG 2.x to 3.0. And further clear that it's not the ideal way forward for intraversion changes (3.0 to 3.1).

**Then I realize I was "burying my lead"** — a tendency I have to lay out foundation but at the expense of putting my main points toward the end of the article or post. 

## Start Reading Here &darr;
I went back and edited my initial post to add some clarification; The main points were the ideas of sectional migration, but  more importantly, "reverse grandfathering" (which was the name I thought of at the time) which today I think is better named as the "New Sibling Paradigm" or grandchild-ing, as a way to incorporate new guidelines without breaking existing sites.

#### Part of getting more sites to conform is enabling conformance to make it easy to do so.

I am quoting the new material added to my post below, so that it appears in the emails, as this chunk better describes the intent:

> #### Exploring the New Siblings Concept
As an example of the concept, [a proposal we were discussing earlier this year](https://github.com/Myndex/SAPC-APCA/discussions/31#discussion-3695553) that I am told can not be done due to the WCAG 2.x charter, is a parallel group of SCs to replace as a complete alternate the 1.4.x SCs on contrast.
>
> Here is the brief proposal for creating a complete set of 1.5.x SCs using APCA as a replacement that a site can choose to use instead of the set of 1.4.3 SCs. While the charter may not allow this, the idea was that a site could choose the SC group, either all the 1.4.x SCs, OR all the 1.5.x SCs.
>
> https://github.com/Myndex/SAPC-APCA/discussions/31#discussion-3695553
>
> Thus, nothing would "break", as it was a choice left up to the site as to which set to conform to. I originally thought this to be possible, as for instance 2.1 added 1.4.11 non text, which itself is not backwards compatible (a site that is conforming to 2.0 can fail 2.1 — that is not backwards compatible, only forwards compatible adm requiring additional work to conform.
>
> The purpose of this post is not to revisit that as an idea to give more life to WCAG 2, but as a consideration as to how to deal with newer technologies for WCAG 3. Here's an abstract example that may have less emotional impact:
>
> #### WobblyWidgets Example
> Let's say mythical GW 3.0 has guideline 4.12 "WobblyWidgets". A lot of time and effort when into it, but technology shifts led to diminishing relevance, and a new parallel alternate guideline 4.17 "StableWidgets" was created. But it is not compatible with 4.12 _WobblyWidgets_ and further, sites like "WobbleSample.com" are entrenched around _WobblyWIdgets_ as is their userbase, but other sites like "StillSamples.com" are pushing for _StableWidgets_.
>
> With the New Sibling paradigm, _WobbleSample.com_ can choose to continue to use 4.12 WobblyWidgets, but importantly,  _StillSamples.com_ can choose to conform to 4.17 StableWidgets, and literally ignore 4.12
>
> #### Mechanism for Testing
> How does a test reconcile this? The first that pops to mind is the use of meta tags as indicated earlier:
> 
> In this example: ` <meta GW3.0="1-11,13-19"> ` the site is using all GW guidelines 1 to 19 except skipping 12. And yea, there's certainly a better syntax for this, this is only illustrative.
> 
> It is definitely a need for this organization to add a flexibility into the process like this, to allow sites to conform to new guidelines as they emerge, while not also breaking existing sites.
 
-----

I hope the example is helpful.

**Comment by alastc** [comment]
>  I originally thought this to be possible, as for instance 2.1 added 1.4.11 non text, which itself is not backwards compatible (a site that is conforming to 2.0 can fail 2.1 — that is not backwards compatible, only forwards compatible adm requiring additional work to conform.

The context for which backwards compatibility has been important to external stakeholders (e.g. legislators), has been: **If you pass 2.1, you should automatically pass 2.0.**

Therefore it has been ok to take an additive approach, adding more SCs, but we can't weaken or mis-align a previous SC.

As mentioned, that has made things more difficult to update.

The sibling concept is interesting, but would be a secondary decision behind: Do we commit to backwards compatibility? If not, then we need to determine how to mitigate the impacts with that or another method.

**Comment by Myndex** [comment]
Hi Alastair @alastc 

> _The context for which backwards compatibility has been important to external stakeholders (e.g. legislators), has been: **If you pass 2.1, you should automatically pass 2.0.**  Therefore it has been ok to take an additive approach, adding more SCs, but we can't weaken or mis-align a previous SC._

Yes, I understand. In what I was thinking as a possibility in the linked proposal was a parallel 1.5x series that could be used as an _optional alternate_ to the 1.4.x SCs, thus, the 1.4.x would not change at all and therefore be backwards compatible. The 1.5 series would substantially improve readability, but only for math reasons would not itself backwards compatible. Thus the thought was as an optional alternative, a site could choose to switch to use 1.5.x instead of the 1.4.x — and as it would be option, and 1.4.x would still be there to provide backwards compatibility, I'd think the stakeholders would favor that.

And that was the genesis of the new-sibling concept. If it's not possible with WCAG 2, I do see it as a beneficial method for WCAG 3 and future revisions.

> _As mentioned, that has made things more difficult to update._

And frustrating - demonstrably, APCA for WCAG 3 greatly improves readability over WCAG 2, but due to math reasons that have nothing to do with actual accessibility, it is not backwards compatible.

> _The sibling concept is interesting, but would be a secondary decision behind: Do we commit to backwards compatibility? If not, then we need to determine how to mitigate the impacts with that or another method._

One of the problems in answering that question is the abstract nature and unknowableness of the future and technology shifts. Committing to backwards compatibility requires a well tuned crystal ball. But as I am hoping to indicate, the benefits that a stakeholder might desire in a WCAG 2 style backwards compatibility are I believe addressed with the new-sibling concept...


Thank you

Andy

**Comment by alastc** [comment]
PR updated based on meeting comments, ready for approval.
