### ISSUE TITLE
Definition of Disability

### ISSUE THREAD

**Issue by mikecrabb** [w3c/silver#6]
Brought up in Silver Meeting (29 May). We need to come up with a definition of Disability that is to be used within Silver. This issue is to look at different definitions and to discuss this in more detail

**Comment by mikecrabb** [comment]
[Americans with Disabilities Act (ADA)](https://www.ada.gov/cguide.htm)

> An individual with a disability is defined by the ADA as a person who has a physical or mental impairment that substantially limits one or more major life activities, a person who has a history or record of such an impairment, or a person who is perceived by others as having such an impairment. The ADA does not specifically name all of the impairments that are covered.

**Comment by jspellman** [comment]
I propose that we not treat it as a formal definition, as that could delay us for a long time.  I propose adding a sentence to the introduction that says: "Disabilities can be permanent, temporary, or situational. Most of the requirements in Silver prioritize the needs of permanent disabilities, but the requirements can also apply to temporary or situational disabilities. "

**Comment by chaals** [comment]
In general I think we should be prepared to take a broader rather than narrower view of what is a disability, but that is something I think we should formally agree on as a design principle.

I don't think we need the second sentence. Disabilities come in a variety of forms, and mean different people have a variety of specific needs. 

The question we address in Silver is

"What can I do to meet the needs of people with disabilities, and how do I know if I did it?".

So we really need to define the needs. Rather than getting into detailed questioning of what caused them, I think we should focus on establishing that given needs are real, and thus impact the potential set of solutions we offer. So we can leave "disability" as a common term that people generally understand in roughly the same way, and save time arguing over the precise boundaries.
