### ISSUE TITLE
Functional needs for sensory characteristics

### ISSUE THREAD

**Issue by slauriat** [w3c/silver#71]
Draft functional needs for [SC 1.3.3 Sensory Characteristics, SC 1.4.1 Use of Color](https://docs.google.com/document/d/1aCRXrtmnSSTso-6S_IO9GQ3AKTB4FYt9k92eT_1PWX4/edit#heading=h.oks9pxyygjow)
- [x] Assigned: Charles Hall
- [x] Meeting or Work started
- [x] Draft Completed
- [x] Reviewed by Silver group

**Comment by hallmedia** [comment]
**Complete**.

**Process**:
Copy and paste the ‘Benefits’ bullets (or ‘Intent’ statement when no Benefits provided) from each Understanding Doc; then edit the copy to convert disability-first or person-first language into functional needs. Then, add any functional needs that may be unique to the grouping of SC or any that may have been missed in the Understanding Docs.

**Example**:
Original benefit of 1.4.1: “Some older users may not be able to see color well.”
Edited functional need: “Usage with limited color perception due to: human factors (like age); technical factors (like display quality); or contextual factors (like bright ambient light).”
